/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UploadfilesImport } from './routes/uploadfiles'
import { Route as SignupImport } from './routes/signup'
import { Route as SettingsImport } from './routes/settings'
import { Route as FillformsImport } from './routes/fillforms'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const UploadfilesRoute = UploadfilesImport.update({
  id: '/uploadfiles',
  path: '/uploadfiles',
  getParentRoute: () => rootRoute,
} as any)

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const FillformsRoute = FillformsImport.update({
  id: '/fillforms',
  path: '/fillforms',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/fillforms': {
      id: '/fillforms'
      path: '/fillforms'
      fullPath: '/fillforms'
      preLoaderRoute: typeof FillformsImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/uploadfiles': {
      id: '/uploadfiles'
      path: '/uploadfiles'
      fullPath: '/uploadfiles'
      preLoaderRoute: typeof UploadfilesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fillforms': typeof FillformsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/uploadfiles': typeof UploadfilesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fillforms': typeof FillformsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/uploadfiles': typeof UploadfilesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/fillforms': typeof FillformsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/uploadfiles': typeof UploadfilesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fillforms' | '/settings' | '/signup' | '/uploadfiles'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fillforms' | '/settings' | '/signup' | '/uploadfiles'
  id: '__root__' | '/' | '/fillforms' | '/settings' | '/signup' | '/uploadfiles'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FillformsRoute: typeof FillformsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  UploadfilesRoute: typeof UploadfilesRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FillformsRoute: FillformsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  UploadfilesRoute: UploadfilesRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/fillforms",
        "/settings",
        "/signup",
        "/uploadfiles"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/fillforms": {
      "filePath": "fillforms.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/uploadfiles": {
      "filePath": "uploadfiles.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
